#!/usr/bin/env python3
"""
Turn a BDF bitmap font into the C header the status screen draws with.

    python gen_font.py spleen-8x16.bdf spleen_8x16.h

Only printable ASCII (32..126) is kept, one byte per row, MSB on the left.
Spleen is BSD-2-Clause; its notice is copied into the generated header.
"""
import sys

def parse_bdf(path):
    glyphs, props, license_lines = {}, {}, []
    with open(path, encoding='utf-8') as handle:
        lines = handle.read().splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith('COMMENT'):
            license_lines.append(line[len('COMMENT'):].strip())
        elif line.startswith('FONTBOUNDINGBOX'):
            props['w'], props['h'] = map(int, line.split()[1:3])
        elif line.startswith('STARTCHAR'):
            code, rows = None, []
            while not lines[i].startswith('ENDCHAR'):
                if lines[i].startswith('ENCODING'):
                    code = int(lines[i].split()[1])
                elif lines[i].startswith('BITMAP'):
                    i += 1
                    while not lines[i].startswith('ENDCHAR'):
                        rows.append(int(lines[i].strip(), 16))
                        i += 1
                    i -= 1
                i += 1
            if code is not None:
                glyphs[code] = rows
        i += 1
    return glyphs, props, license_lines

def main(src, dst):
    glyphs, props, license_lines = parse_bdf(src)
    w, h = props['w'], props['h']
    assert w == 8, "the renderer expects 8-pixel-wide glyphs"
    name = dst.rsplit('.', 1)[0].upper()
    out = []
    out.append('// Generated by gen_font.py from %s -- do not edit by hand.' % src)
    out.append('//')
    for text in license_lines:
        if text.startswith('*') or text.startswith('/*') or text.startswith('*/'):
            out.append('// ' + text.lstrip('/* ').rstrip())
    out.append('#pragma once')
    out.append('#include <stdint.h>')
    out.append('')
    out.append('#define %s_WIDTH %d' % (name, w))
    out.append('#define %s_HEIGHT %d' % (name, h))
    out.append('#define %s_FIRST 32' % name)
    out.append('#define %s_LAST 126' % name)
    out.append('')
    out.append('// One byte per row, bit 7 is the leftmost pixel.')
    out.append('static const uint8_t %s[95][%d] PROGMEM = {' % (name, h))
    for code in range(32, 127):
        rows = glyphs.get(code, [0] * h)
        rows = (rows + [0] * h)[:h]
        label = chr(code) if code != 92 else 'backslash'
        out.append('    {%s}, // %d %s' % (', '.join('0x%02X' % r for r in rows), code, label))
    out.append('};')
    with open(dst, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(out) + '\n')
    print('wrote', dst, 'with', len(glyphs), 'glyphs available,', 95, 'kept')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
